// <auto-generated />
using System;
using Dash.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dash.Entity.Migrations
{
    [DbContext(typeof(DSDContext))]
    partial class DSDContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dash.Entity.Objects.DSDAccessibleSite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AccessibleSiteIdId");

                    b.Property<Guid?>("SiteIdId");

                    b.HasKey("Id");

                    b.HasIndex("AccessibleSiteIdId");

                    b.HasIndex("SiteIdId");

                    b.ToTable("AccessibleSite");
                });

            modelBuilder.Entity("Dash.Entity.Objects.DSDDataShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DataShareCode");

                    b.Property<Guid?>("OwnerSiteIdId");

                    b.Property<int>("Status");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("OwnerSiteIdId");

                    b.ToTable("DataShares");
                });

            modelBuilder.Entity("Dash.Entity.Objects.DSDSite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccessCode");

                    b.Property<DateTime>("AccessCodeEndDate");

                    b.Property<string>("SiteAddress");

                    b.Property<short>("Status");

                    b.HasKey("Id");

                    b.ToTable("Site");
                });

            modelBuilder.Entity("Dash.Entity.Objects.DSDUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Firstname");

                    b.Property<string>("Lastname");

                    b.Property<string>("Password");

                    b.Property<short>("Status");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Dash.Entity.Objects.DSDAccessibleSite", b =>
                {
                    b.HasOne("Dash.Entity.Objects.DSDSite", "AccessibleSiteId")
                        .WithMany()
                        .HasForeignKey("AccessibleSiteIdId");

                    b.HasOne("Dash.Entity.Objects.DSDSite", "SiteId")
                        .WithMany()
                        .HasForeignKey("SiteIdId");
                });

            modelBuilder.Entity("Dash.Entity.Objects.DSDDataShare", b =>
                {
                    b.HasOne("Dash.Entity.Objects.DSDSite", "OwnerSiteId")
                        .WithMany()
                        .HasForeignKey("OwnerSiteIdId");
                });
#pragma warning restore 612, 618
        }
    }
}
